spring:
  application:
    name: dicebound-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 0
      idle-timeout: 10000  # 10 seconds
      max-lifetime: 30000  # 30 seconds
      connection-timeout: 3000

telegram:
  signup-username: ${SIGNUP_TELEGRAM}
server:
  port: 8081
