spring:
  application:
    name: dicebound-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      max-lifetime: 1800000

telegram:
  signup-username: ${SIGNUP_TELEGRAM}
server:
  port: 8081
